name: CDK tests

on:
  pull_request:
    branches:
      - main
      - v1
      - v3
  workflow_dispatch: {}

jobs:
  cdk-synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Synthesize bootstrap
        working-directory: cdk
        run: |
          npm ci
          npx cdk synth bootstrap
          ls -lh cdk.out/        

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install cf2tf
        run: |
          pip install cf2tf

      - name: Convert CFN to Terraform
        working-directory: cdk
        run: |
          cf2tf cdk.out/bootstrap.template.json > main.tf
          ls -lh main.tf

      - name: Upload Terraform
        uses: actions/upload-artifact@v4
        with:
          name: terraform-iac
          path: cdk/main.tf

  cdk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: |
          cd cdk
          npm ci
          npm run test
