name: CDK tests

on:
  pull_request:
    branches:
      - main
      - v1
      - v3
  workflow_dispatch: {}

jobs:
  cdk-synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Synthesize BedrockChatStack
        working-directory: cdk
        run: |
          cd cdk
          npm ci
          npx cdk synth BedrockChatStack > BedrockChatStack.template.yaml
          ls -lh BedrockChatStack.template.json
      - name: Upload template
        uses: actions/upload-artifact@v3
        with:
          name: bedrockchat-template
          path: cdk/BedrockChatStack.template.json
  cdk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: |
          cd cdk
          npm ci
          npm run test
